// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview AI-based safety assessment tool for food products based on user health profiles.
 *
 * - assessFoodSafety - A function that assesses the safety of a food product for a given user.
 * - AISafetyAssessmentInput - The input type for the assessFoodSafety function.
 * - AISafetyAssessmentOutput - The return type for the assessFoodSafety function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AISafetyAssessmentInputSchema = z.object({
  ingredients: z
    .string()
    .describe('A list of ingredients of the food product.'),
  healthProfile: z
    .string()
    .describe(
      'The user health profile, including allergies, health conditions, and dietary preferences.'
    ),
});
export type AISafetyAssessmentInput = z.infer<typeof AISafetyAssessmentInputSchema>;

const AISafetyAssessmentOutputSchema = z.object({
  verdict: z
    .enum(['Safe', 'Not Safe', 'Moderate'])
    .describe('The safety verdict for the food product.'),
  reasoning: z.string().describe('The reasoning behind the safety verdict.'),
  warnings: z.array(z.string()).describe('A list of potential concerns or warnings.'),
  alternatives: z.array(z.object({
    name: z.string().describe('The name of the alternative product.'),
    reason: z.string().describe('The reason why this is a good alternative.')
  })).describe('A list of alternative food product suggestions, if applicable.'),
});

export type AISafetyAssessmentOutput = z.infer<typeof AISafetyAssessmentOutputSchema>;

export async function assessFoodSafety(input: AISafetyAssessmentInput): Promise<AISafetyAssessmentOutput> {
  return aiSafetyAssessmentFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiSafetyAssessmentPrompt',
  input: {schema: AISafetyAssessmentInputSchema},
  output: {schema: AISafetyAssessmentOutputSchema},
  prompt: `You are an AI food safety expert. Assess the safety of a food product based on the user's health profile and the product's ingredients.

Health Profile: {{{healthProfile}}}
Ingredients: {{{ingredients}}}

Provide a safety verdict (Safe, Not Safe, or Moderate), clear reasoning, a list of warnings (if any), and a list of alternative suggestions if the product is not suitable.

Your output must be in a valid JSON format that adheres to the following schema:
`,
});

const aiSafetyAssessmentFlow = ai.defineFlow(
  {
    name: 'aiSafetyAssessmentFlow',
    inputSchema: AISafetyAssessmentInputSchema,
    outputSchema: AISafetyAssessmentOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
